import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Footer from '../components/footer'
import NavBar from '../components/navbar'
import ProfileImageArtDirection from '../components/profile-image'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles['container']}>
        <div className={styles['content']}>
          <NavBar />

          <main className={styles['main']}>
            <div className={styles['main__pitch']}>
              <h1>
                Hi, I am Oleksii.
              </h1>
              <h2 className={styles['mt-2']}>
                Software engineer, technology enthusiast, and avid learner based in Sweden.
              </h2>
            </div>
            <ProfileImageArtDirection className={styles['main__img']} />
          </main>
        </div>

        <Footer />
      </div>
    </>
  )
}

export default Home
