import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Footer from '../components/footer'
import NavBar from '../components/navbar'
// import styles from '../styles/HomeGrid.module.scss'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles['container']}>
        <Image
          className={styles['hero-img']}
          src="/images/hero.jpg"
          alt="Swedish landscape background"
          layout="fill"
          objectFit="cover"
          priority
        />

        <div className={styles['content']}>
          <NavBar />

          <main className={styles['main']}>
            <div className={styles['main__pitch']}>
              <h1>
                Hi, I am Oleksii.
              </h1>
              <h2 className={styles['mt-2']}>
                Software engineer, technology enthusiast, and avid learner based in Sweden.
              </h2>
            </div>
            <div className={styles['main__img']}>
              <Image
                className={styles.image}
                src="/images/oleksii-desktop.png"
                alt="Oleksii Shevtsov"
                width={500}
                height={500}
                priority
              />
            </div>
          </main>
        </div>

        <Footer />
      </div>
    </>
  )
}

export default Home
